version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  base-directory: frontend/build
  files:
    - "**/*"
