version: 0.2

phases:
  install:
    commands:
      - cd sam-app
      - npm install
  build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - sam-app/template-export.yml
